### ISSUE TITLE
values aren't smooth

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#53]
the values of the climate variables aren't smooth across a smooth elevation gradient. I'm guessing there is a small problem with the lapse rates. 

e.g. Tave over a test dem: 

![image](https://user-images.githubusercontent.com/17104005/160491999-5a3410ef-827b-4b31-8d81-bab23697761d.png)

this is the dem itself: 

![image](https://user-images.githubusercontent.com/17104005/160492055-d2b4fbec-f8f9-4be9-a2ce-59ba6f6fe33e.png)

here is code to reproduce the example (the dem is in the base code folder): 

```
dem <- raster(paste("dem_test.tif", sep=""))
X <- dem
values(X) <- NA

dem.pts <- rasterToPoints(dem, spatial=T) 
dem.pts <- as.data.frame(dem.pts) 
land <- which(!is.na(values(dem)))
xyz <- data.frame(lon=dem.pts$x, lat=dem.pts$y, elev=dem.pts[,1])

# Select GCM
gcm <- gcm_input(
  gcm = gcms[5],
  ssp = c("ssp245"),
  period = "2041_2060",
  max_run = 0
)

# projected normals
projnormals <- data.frame(downscale(
  xyz = xyz,
  normal = normal,
  gcm = gcm,
  var = vars.all
))

var="Tave"
par(mar=c(0,0,0,1))
for(var in names(projnormals)[-c(1:5)]){
  run.0 <- projnormals[which(projnormals$GCM=="EC.Earth3" 
                          & projnormals$SSP=="ssp245" 
                          & projnormals$RUN=="ensembleMean" 
                          & projnormals$PERIOD=="2041_2060"), 
                    which(names(projnormals)==var)]
  
  values(X)[land] <- run.0
  plot(X)
  mtext(var, cex=1.5, line=-1.5, adj=0.05)
  
}

```

**Comment by meztez** [comment]
```r
values(dem)[land[1:50]] == xyz[1:50,3]
```

All return FALSE, not sure we can juste plug the values back in there at the end with values(X)[land] <- run.0

**Comment by meztez** [comment]
There was a single points value extraction that was still done with the simple method instead of linear. Switching it to "bilinear" gives something like.
![Screenshot from 2022-03-28 20-21-51](https://user-images.githubusercontent.com/31039074/160508467-fcb675bf-0677-45e2-849e-825b5efd9dfd.png)

This is around the extractions we do to apply the lapse rates adjustments. Unclear to me from the paper alone which method is used to determine final lapse rates for each point.

Here is the same raster with the values from climateNA.
(will edit and add it, need to switch OS)

**Comment by cmahony** [comment]
looks like the issue is resolved with bilinear extraction. the differences to climate NA are very subtle and not important. one reason for the difference may be that climateNA uses a 4km grid for the reference normals.

**Comment by meztez** [comment]
Oh, that could definitly explain it.

**Comment by cmahony** [comment]
the issue is resolved so i'm closing it.
