### ISSUE TITLE
Future work: DD5 equations

### ISSUE THREAD

**Issue by cmahony** [bcgov/climR-pnw#63]
I received this message from Sarah Endicott @see24. this is out of scope for Boostao, its an issue for future work. 

> I noticed that you have the derived variables from Wang 2016 in your repo and I wanted to give you a heads up that I found an issue in that paper when I implemented those functions in R a couple years ago. 
> I emailed Tongli about it and he agreed the paper was wrong.
> 
> First of all in the paper the DD5 equation looks like this:
>  
> ![dd5](https://user-images.githubusercontent.com/39161074/137031204-6ea0583f-e46b-4973-a2fd-ce27fdec017d.png)
> I believe the directions of the > and < are reversed because it should be a straight line at temperatures above k and a curve heading to zero below k.
> 
> Secondly, when I calculated DD5 using the parameters in the paper the DD5 was higher than it should be for many locations. When I investigated the issue I found that a graph made using the parameters in the paper did not match the graph for DD5 vs Jan mean temperature in the paper (see graph below left, blue line). I discovered that if I exchanged the parameters b and T0 from the S2 Table the graph appeared to match the paper (see graphs below red lines, and table below).
>   
> ![dd5_2](https://user-images.githubusercontent.com/39161074/137031246-00ae01d0-92bb-4579-b18e-e1cc3b7c1167.png)
> ![dd5_3](https://user-images.githubusercontent.com/39161074/137031255-afec0da9-ac7a-4abf-97cd-396237d51f7b.png)
> ![dd5_4](https://user-images.githubusercontent.com/39161074/137031264-5d5bccc6-0489-456b-8ab5-21c6cc57ccda.png)
> 
> Also if you haven't coded the equations yet I might be able to share my code but would have to check with my employer so let me know if you are interested!

**Comment by meztez** [comment]
lets just fix it now

Bruno
________________________________
From: Colin Mahony ***@***.***>
Sent: Wednesday, March 30, 2022 4:51:21 PM
To: bcgov/climR-pnw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bcgov/climR-pnw] Future work: DD5 equations (Issue #63)


I received this message from Sarah Endicott @see24<https://github.com/see24>. this is out of scope for Boostao, its an issue for future work.

I noticed that you have the derived variables from Wang 2016 in your repo and I wanted to give you a heads up that I found an issue in that paper when I implemented those functions in R a couple years ago.
I emailed Tongli about it and he agreed the paper was wrong.

First of all in the paper the DD5 equation looks like this:

[dd5]<https://user-images.githubusercontent.com/39161074/137031204-6ea0583f-e46b-4973-a2fd-ce27fdec017d.png>
I believe the directions of the > and < are reversed because it should be a straight line at temperatures above k and a curve heading to zero below k.

Secondly, when I calculated DD5 using the parameters in the paper the DD5 was higher than it should be for many locations. When I investigated the issue I found that a graph made using the parameters in the paper did not match the graph for DD5 vs Jan mean temperature in the paper (see graph below left, blue line). I discovered that if I exchanged the parameters b and T0 from the S2 Table the graph appeared to match the paper (see graphs below red lines, and table below).

[dd5_2]<https://user-images.githubusercontent.com/39161074/137031246-00ae01d0-92bb-4579-b18e-e1cc3b7c1167.png>
[dd5_3]<https://user-images.githubusercontent.com/39161074/137031255-afec0da9-ac7a-4abf-97cd-396237d51f7b.png>
[dd5_4]<https://user-images.githubusercontent.com/39161074/137031264-5d5bccc6-0489-456b-8ab5-21c6cc57ccda.png>

Also if you haven't coded the equations yet I might be able to share my code but would have to check with my employer so let me know if you are interested!

**Comment by cmahony** [comment]
sounds great. thanks bruno

**Comment by meztez** [comment]
is it the same for the others? are b and T0 all reversed?

**Comment by cmahony** [comment]
good question. i'll ask tongli.

**Comment by see24** [comment]
I didn't notice any other issues when I found the DD5 one but I don't think I tested all of them. Probably worth making plots similar to the one in the paper for all of them to double check

**Comment by see24** [comment]
@cmahony No problem! It took me awhile to figure out so just glad it is useful to someone else!

**Comment by meztez** [comment]
```r
plot(-30:30, climRpnw:::calc_DD_below_0(1, -30:30), type = "l")
plot(-30:30, climRpnw:::calc_DD_below_18(5, -30:30), type = "l")
plot(-30:30, climRpnw:::calc_DD_above_5(1, -30:30, "All") , type = "l")
plot(-30:30, climRpnw:::calc_DD_above_18(8, -30:30, "All"), type = "l")
```

In case you want to analyse them

**Comment by cmahony** [comment]
sweet.

**Comment by meztez** [comment]
I've checked, I believe they are all reversed. I'll change the csv.

**Comment by cmahony** [comment]
DD_below should be shaped like DD_above, but flipped on the y axis at the threshold X value.

**Comment by meztez** [comment]
it's already in

**Comment by cmahony** [comment]
I ran the map comparisons to ClimateBC, and all DD variables look excellent, except DD5 in the cool seasons (March, April, November) where DD5 is zero in climR. April and May DD5 shown below for illustration. 


![climR tests compareClimBC DD5_04](https://user-images.githubusercontent.com/17104005/161080674-4c492b6f-9508-4e1c-9fab-de792461230b.png)


![climR tests compareClimBC DD5_05](https://user-images.githubusercontent.com/17104005/161080684-c3318a31-9978-4e8f-93fd-1c02234e120d.png)

**Comment by meztez** [comment]
Fixed it

**Comment by cmahony** [comment]
great success. 

![climR tests compareClimBC DD5_04](https://user-images.githubusercontent.com/17104005/161084914-9f20db3d-32a8-4496-862a-fbcf46b0f34b.png)
